# DEFAULT MAIN SETTINGS:
DEFAULT_ADDRESS = '127.0.0.1'
DEFAULT_PORT = 7777
DEFAULT_ENCODING = 'utf-8'
DEFAULT_MAX_PACKAGE_LENGTH = 1024
DEFAULT_MAX_CONNECTIONS = 5


# JIM PROTOCOL MAIN KEYS:
ACTION = 'action'
TIME = 'time'
USER = 'user'
ACCOUNT_NAME = 'account_name'


# OTHER PROTOCOL KEYS:
PRESENCE = 'presence'
RESPONSE = 'response'
ERROR = 'error'
RESPONDEFAULT_IP_ADDRESSEE = 'respondefault_ip_addressee'
